# Generated by Django 2.2.7 on 2019-11-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=100)),
                ('menu', models.CharField(max_length=200)),
                ('order_times', models.IntegerField()),
                ('average', models.FloatField()),
            ],
            options={
                'db_table': 'menu_analysis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MenuImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=100)),
                ('menu', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'menu_img',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wordclouds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=100)),
                ('pn', models.CharField(max_length=10)),
                ('wordcloud', models.TextField()),
            ],
            options={
                'db_table': 'wordclouds',
                'managed': False,
            },
        ),
    ]
