# Generated by Django 2.2.7 on 2019-11-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=100)),
                ('review_num', models.IntegerField()),
            ],
            options={
                'db_table': 'restaurants',
                'managed': False,
            },
        ),
    ]
