# Generated by Django 2.2.7 on 2019-11-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_restaurants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=100)),
                ('menu', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'menus',
                'managed': False,
            },
        ),
    ]
